apiVersion: v1 
kind: Deployment 
metadata:
  name: work-api
  labels: 
  app: work
spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: work 
  template:
    metadata:
      labels:
        app: work 
        spec: 
        containers:
        - name: work 
          image: clippr.azurecr.io/work-api:latest
          ports: 
          - containerPort: 80
---
# Sidecar Deployment of email api
apiVersion: v1 
kind: pod
metadata:
  name: email-api
  labels:
  app: email
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: email 
  template:
    metadata:
      labels:
        app: email
        spec: 
        containers:
        - name: work 
          image: clippr.azurecr.io/email-api:latest
          ports: 
          - containerPort: 80

